from typing import Annotated, Sequence, Dict, Any
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from langchain_openai import ChatOpenAI
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState

from tradingagents.utils.logging_init import get_logger
logger = get_logger("default")


def merge_dicts(left: Dict, right: Dict) -> Dict:
    if left is None:
        left = {}
    if right is None:
        right = {}
    merged = dict(left)
    for key, value in right.items():
        if key in merged and merged[key] and not value:
            continue
        merged[key] = value
    return merged


def merge_debate_state(left: Dict, right: Dict) -> Dict:
    if left is None:
        left = {}
    if right is None:
        right = {}
    merged = dict(left)
    for key, value in right.items():
        merged[key] = value
    return merged


class InvestDebateState(TypedDict):
    bull_history: Annotated[str, "Bullish Conversation history"]
    bear_history: Annotated[str, "Bearish Conversation history"]
    history: Annotated[str, "Conversation history"]
    current_response: Annotated[str, "Latest response"]
    judge_decision: Annotated[str, "Final judge decision"]
    count: Annotated[int, "Length of the current conversation"]


class RiskDebateState(TypedDict):
    risky_history: Annotated[str, "Risky Agent's Conversation history"]
    safe_history: Annotated[str, "Safe Agent's Conversation history"]
    neutral_history: Annotated[str, "Neutral Agent's Conversation history"]
    history: Annotated[str, "Conversation history"]
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    current_risky_response: Annotated[str, "Latest response by the risky analyst"]
    current_safe_response: Annotated[str, "Latest response by the safe analyst"]
    current_neutral_response: Annotated[str, "Latest response by the neutral analyst"]
    judge_decision: Annotated[str, "Judge's decision"]
    count: Annotated[int, "Length of the current conversation"]


class AgentState(MessagesState):
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    trade_date: Annotated[str, "What date we are trading at"]
    company_name_resolved: Annotated[str, "Cached resolved company name to avoid repeated API calls"]

    sender: Annotated[str, "Agent that sent this message"]

    market_report: Annotated[str, "Report from the Market Analyst"]
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    news_report: Annotated[str, "Report from the News Researcher of current world affairs"]
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    market_tool_call_count: Annotated[int, "Market analyst tool call counter"]
    news_tool_call_count: Annotated[int, "News analyst tool call counter"]
    sentiment_tool_call_count: Annotated[int, "Social media analyst tool call counter"]
    fundamentals_tool_call_count: Annotated[int, "Fundamentals analyst tool call counter"]

    investment_debate_state: Annotated[
        InvestDebateState, merge_debate_state
    ]
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    risk_debate_state: Annotated[
        RiskDebateState, merge_debate_state
    ]
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]

    master_reports: Annotated[Dict[str, str], merge_dicts]
    master_tool_call_counts: Annotated[Dict[str, int], merge_dicts]
    master_data_quality: Annotated[Dict[str, Dict[str, Any]], merge_dicts]
    master_quantitative_results: Annotated[Dict[str, Dict[str, Any]], merge_dicts]

    master_consensus_report: Annotated[str, "Master consensus summary report"]

    china_market_report: Annotated[str, "China market analysis report"]

    prefetched_fundamentals_data: Annotated[str, "Pre-fetched fundamentals data shared by all master analysts"]
    prefetched_market_data: Annotated[str, "Pre-fetched market data for reference"]
    prefetched_quant_data: Annotated[str, "Pre-fetched structured quantitative data for quant analyzers"]
    fundamental_snapshot: Annotated[Dict[str, Any], merge_dicts]
